# app.yaml

runtime: python311
env: standard
entrypoint: gunicorn -b :$PORT interfaz_pr.wsgi:application --pythonpath interfaz_pr

runtime_config:
  python_version: 3
  
handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: staticfiles/
- url: /media   
  static_dir: mediafiles/
- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "interfaz_pr.settings"
  SECRET_KEY: "kf7e05ufycf&xd7y)b+ssxg^08$i8&n^5w0y@60w*+)@+o=ejq"
  GS_BUCKET_NAME: "igniteaibucket01"
beta_settings:
  cloud_sql_instances: predictbuild:europe-southwest1:predictbuild-instancia