# Generated by Django 5.1.3 on 2026-06-22 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_user_groups_permissions_and_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "ciudades",
                "db_table": "ciudades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("precio_m2", models.FloatField(blank=True, default=0, null=True)),
                (
                    "ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distritos",
                        to="home.ciudad",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "distritos",
                "db_table": "distritos",
                "ordering": ["nombre"],
                "unique_together": {("nombre", "ciudad")},
            },
        ),
        migrations.CreateModel(
            name="Barrio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("precio_m2", models.FloatField(blank=True, default=0, null=True)),
                (
                    "distrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barrios",
                        to="home.distrito",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "barrios",
                "db_table": "barrios",
                "ordering": ["nombre"],
                "unique_together": {("nombre", "distrito")},
            },
        ),
        migrations.CreateModel(
            name="Calle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("precio_m2", models.FloatField(blank=True, default=0, null=True)),
                (
                    "barrio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calles",
                        to="home.barrio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "calles",
                "db_table": "calles",
                "ordering": ["nombre"],
                "unique_together": {("nombre", "barrio")},
            },
        ),
    ]
