# Generated by Django 5.1.3 on 2026-06-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_ciudad_distrito_barrio_calle"),
    ]

    operations = [
        migrations.AddField(
            model_name="valoracion",
            name="correccion_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="valoracion",
            name="precio_corregido",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
