# Generated by Django 5.1.3 on 2026-06-27 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_valoracion_correccion_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="tipo",
            field=models.CharField(
                choices=[("informe", "Informe"), ("dossier", "Dossier")],
                default="informe",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="informe",
            name="valoracion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="informes",
                to="home.valoracion",
            ),
        ),
    ]
